name: "Mirror a repo's latest tag to FlakeHub."
run-name: Mirror ${{ inputs.repo }}@${{ inputs.tag }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to publish."
        type: "string"
        required: true
      repo:
        description: "The repo to publish, in the format of Owner/Repo."
        type: "string"
        required: true

jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: "actions/checkout@v5"
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.tag }}

      - name: Set FlakeHub name
        id: flake-name
        run: echo "name=jhofer-cloud/$(echo '${{ inputs.repo }}' | tr '/' '-')" >> $GITHUB_OUTPUT

      - uses: "DeterminateSystems/nix-installer-action@main"
      - uses: "DeterminateSystems/flakehub-cache-action@main"
      - uses: "DeterminateSystems/flakehub-push@main"
        with:
          name: ${{ steps.flake-name.outputs.name }}
          visibility: public
          repository: ${{ inputs.repo }}
          tag: ${{ inputs.tag }}
          log-directives: flakehub_push=trace
          logger: pretty
